
// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

import { type RouteType as Route_0 } from "./src/pages/posts/[postId]";
import type { InferRoute, StaticRoute } from "next-typesafe-url";

declare module "@@@next-typesafe-url" {
  interface DynamicRouter {
    "/posts/[postId]": InferRoute<Route_0>;
  }

  interface StaticRouter {
    "/": StaticRoute;
  }
}
